# Generated by Django 4.2.3 on 2023-08-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('temail', models.CharField(max_length=200)),
                ('tpassword', models.CharField(max_length=200)),
                ('tphone', models.IntegerField()),
                ('join_date', models.DateField()),
                ('t_qualification', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('tcourses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courses')),
            ],
        ),
    ]
