# Generated by Django 4.2.3 on 2023-07-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('fees', models.FloatField(max_length=200)),
                ('comment', models.TextField()),
                ('duration', models.CharField(max_length=150)),
            ],
        ),
    ]
